"""Add execution_time column in 'action' table

Revision ID: 3aa3d81aded1
Revises: 7a301a687618
Create Date: 2024-01-23 22:15:52.770274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3aa3d81aded1"
down_revision: Union[str, None] = "7a301a687618"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("action", sa.Column("execution_time", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("action", "execution_time")
    # ### end Alembic commands ###
