"""Fix typo in resource_name column

Revision ID: 7a301a687618
Revises: 2ee513caeeee
Create Date: 2024-01-23 22:04:43.549395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a301a687618"
down_revision: Union[str, None] = "2ee513caeeee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("action", sa.Column("resource_name", sa.String(), nullable=True))
    op.drop_column("action", "resouce_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "action",
        sa.Column("resouce_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("action", "resource_name")
    # ### end Alembic commands ###
