version: '3.5'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:14
    command: -p 5432
    expose:
      - 5432
    env_file:
      - ../.env


  bot:
    container_name: bot
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres_db
    env_file:
      - ../.env
    command: ["/app/docker/bot.sh"]
