version: '3.5'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - ../.env-docker

  migrations:
    container_name: alembic_migrations
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres_db
      - prefect_flow
    environment:
      - ENV_STATE=docker
    env_file:
      - ../.env-docker
    command: poetry run alembic upgrade head

  bot:
    container_name: bot
    image: docker-migrations:latest
    depends_on:
      - migrations
    environment:
      - ENV_STATE=docker
    env_file:
      - ../.env-docker
    command: ["/app/docker/bot.sh"]

  prefect_flow:
    container_name: prefect_flow
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - PREFECT_API_KEY=${PREFECT_API_KEY}
        - PREFECT_WORKSPACE_ID=${PREFECT_WORKSPACE_ID}
    depends_on:
      - postgres_db
    env_file:
      - ../.env-docker
    entrypoint: /bin/bash
    command:
      - -c
      - |
        source /app/.env-docker &&
        make auth &&
        make run
