"""Create "action" table

Revision ID: 2ee513caeeee
Revises: dad942c056df
Create Date: 2024-01-18 17:55:43.335526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ee513caeeee"
down_revision: Union[str, None] = "dad942c056df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user", ["telegram_id"])
    op.add_column(
        "user_subscription", sa.Column("telegram_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "user_subscription_user_id_fkey", "user_subscription", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "user_subscription", "user", ["telegram_id"], ["telegram_id"]
    )
    op.drop_column("user_subscription", "user_id")
    op.create_table(
        "action",
        sa.Column("action_id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=True),
        sa.Column("platform_type", sa.String(), nullable=True),
        sa.Column("resouce_name", sa.String(), nullable=True),
        sa.Column("query", sa.String(), nullable=True),
        sa.Column("response", sa.String(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("feedback", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["telegram_id"],
            ["user.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("action_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_subscription",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "user_subscription", type_="foreignkey")
    op.create_foreign_key(
        "user_subscription_user_id_fkey",
        "user_subscription",
        "user",
        ["user_id"],
        ["user_id"],
    )
    op.drop_column("user_subscription", "telegram_id")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_table("action")
    # ### end Alembic commands ###
