"""Initial revision. Create tables

Revision ID: c1e79b635e04
Revises:
Create Date: 2024-01-13 14:51:17.134550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1e79b635e04"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_type",
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("type_name", sa.String(), nullable=False),
        sa.Column("montly_price", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("type_id"),
        sa.UniqueConstraint("type_name"),
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("registered_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_subscription",
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=True),
        sa.Column("valid_from", sa.TIMESTAMP(), nullable=False),
        sa.Column("valid_to", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["subscription_type.type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("subscription_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_subscription")
    op.drop_table("user")
    op.drop_table("subscription_type")
    # ### end Alembic commands ###
