"""Add bio to user table

Revision ID: dad942c056df
Revises: c1e79b635e04
Create Date: 2024-01-17 23:05:19.481607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dad942c056df"
down_revision: Union[str, None] = "c1e79b635e04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription_type", sa.Column("monthly_price", sa.Integer(), nullable=False)
    )
    op.drop_column("subscription_type", "montly_price")
    op.add_column("user", sa.Column("bio", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "bio")
    op.add_column(
        "subscription_type",
        sa.Column("montly_price", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("subscription_type", "monthly_price")
    # ### end Alembic commands ###
