messages:
  welcome: |
    Привет! Я — *KarpovGPT*🤖, бот для помощи в обучении.
    Ты можешь *задавать вопросы* и *получать ответы* на основе курсов!
    А так же я могу помочь *создавать конспекты*👨‍💻!

    *Команды:*
    - /help - показывает эту справку
    - /start - начало диалога

  unknown_message_error: |
    🚫 Я не распознал ваш запрос.

    Чтобы продолжить диалог, пожалуйста, ответьте на одно из предыдущих сообщений или воспользуйтесь командой:
    */find [Канал] [Запрос]*

templates:
  extract: |
    Write the tags for the query below:
    ----------------------------------------
    Query: "{query}"
    ----------------------------------------
    Instruction:
    1) You must use language as in original query
    2) Do not duplicate the query in your response. 
    3) Do not use words from original query in your response, your tags must be new and unique
    4) Write the tags in the order of relevance, separated by commas, without any other characters.

    Examples:
    Query: 'Какой рецепт борща?'
    Answer: 'Кулинария, суп' 

    Query: 'Кто создал ChatGPT?' 
    Answer: 'AI, OpenAI, LLM' 

    Query: 'Что такое МЛ симулятор?'
    Answer: 'Машинное обучение, искусственный интеллект'