messages:
  welcome: |
    Привет! Я — *KarpovGPT*🤖, бот для помощи в обучении.
    Ты можешь *задавать вопросы* и *получать ответы* на основе курсов!
    А так же я могу помочь *создавать конспекты*👨‍💻!

    *Команды:*
    - /help - показывает эту справку
    - /start - начало диалога

  unknown_message_error: |
    🚫 Я не распознал ваш запрос.

    Чтобы продолжить диалог, пожалуйста, ответьте на одно из предыдущих сообщений или воспользуйтесь командой:
    */find [Канал] [Запрос]*
