messages:
  welcome: |
    Привет! Я — *PostFinder*, инструмент, который изменит твое взаимодействие с социальными сетями.
    
    Если вы постоянно теряетесь в ТОННЕ КОНТЕНТА, 
    приходиться листать БЕСКОНЕЧНОЕ количество постов и никак не можете найти ТОТ САМЫЙ пост? То вы пришли в нужное место!

    *Команды:*
    - /help - показывает эту справку
    - /start - начало диалога
    - /find @channel [Запрос] - ищет ответ на Ваш вопрос в указанном канале
  unknown_message_error: |
    🚫 Я не распознал ваш запрос.

    Чтобы продолжить диалог, пожалуйста, ответьте на одно из предыдущих сообщений или воспользуйтесь командой:
    */find [Канал] [Запрос]*

templates:
  extract: |
    Write the tags for the query below:
    ----------------------------------------
    Query: "{query}"
    ----------------------------------------
    Instruction:
    1) You must use language as in original query
    2) Do not duplicate the query in your response. 
    3) Do not use words from original query in your response, your tags must be new and unique
    4) Write the tags in the order of relevance, separated by commas, without any other characters.

    Examples:
    Query: 'Какой рецепт борща?'
    Answer: 'Кулинария, суп' 

    Query: 'Кто создал ChatGPT?' 
    Answer: 'AI, OpenAI, LLM' 

    Query: 'Что такое МЛ симулятор?'
    Answer: 'Машинное обучение, искусственный интеллект'
  
regex:
  youtube:
    video:
      '^https?://(?:www\.)?(?:youtube\.com/watch\?v=|youtu\.be/)([a-zA-Z0-9_-]{11})'
